language: ruby
before_install: gem install bundler -v 1.17.3
script: ./build.sh
branches:
  only:
  - master
rvm:
- 2.6.0
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: dz2F3GW2bQdx3/ajCwda3UUXOGYtd0raylDNUv1ECVXQaC0xc63vAs63rF7n9OaA39P5VzEHST7yKtIrnwgWt0w9XjfYM0MqJxNZgVDNhCgbhj/L3GZ5vujVJ1B1cL/Fmf6zGUytYTbm9RYA3FbpEIzSjdFj+0H+L/w+5k3kjjP89ngqnhwJDvbHTArrg0uaW4ZH+u4sqQ2mJ5sY13pAgYrjUAqp5DPuJ8mta11FyzK8bOsj9RY+GrMSsuZstwrry3IXI0sKFwr1fwcRfyo0zhn9EoOpVk8Cn6X+QOQ0Iq5T3FU7D8W/CeG47U0HoRgA/hcaniwSBlQ47xAOUgx+YG0UdpcKzQK4+nXKQsCoD+sz+yY/GDLACa91e/Sgn+zWQJReeD7X0OdEUIcBBek+7kLOL3cQWe+ThGkseQP9wZ7/fvjykItFcRcffvHA/gajY88KWVqQUSi4dvEHSc5MAtsbLDk5inUF3m/UYpIDNNcKxkLze7kO+0bxu0QHeCAWSNkfQadQusPEYqrQ2vOTXfzithM2G/pDbiXaQelNE3frJj8gVU/753XysGy3NrEndRUKYA2s9+wnGDycSpKdqcpP1ebntjHQMQo8Gd6mx17UUfPo/ZL3sguKkJhxQJucZSnC8r3ZwmmaBKk56ScFpEiupGdzECQ32MGhUlovjj4=