language: ruby
before_install: gem install bundler -v 1.17.3
script: ./build.sh
branches:
  only:
  - master
rvm:
- 2.6.0
notifications:
  email:
    on_success: never
    on_failure: always
env:
  global:
    secure: XtEXY7OvnNxHyAk62u2ITpCq0A70SDWYgvcjHepOMrVdGGJcXAz0JVKXkIgjiOFruwXHFV+MNZcbv78oGSkSrxdMr912GwNZWZiYGZi4osBEi4RpjzURYHiBtq4eZ2+N/KAi8SchzMbxDZKHOI/p4+Z8rOiP5mDMaxBNr4DE6WRnMbewa5kRPsyfkFNZZV/iOnsdBun2A0vCvokiJ3xCXfcYrADJatn7jEXeiRAyqI1SHkPFMdgM4l+ZYOmx/fgVHNiZiJOfFekr/hx98a4ymGIoW9RYEIepQk22eJrenniYXd+EbckbYmtmXqJV8Uyf3Ko60cCdxEvqgWivk+fbLFoKhxaBh3bCUl/8Nu/xpnkOSh+rgjOqeIhk4q0r9s/yVhO60PHfoj2BYCQUQas5YcQXlGMU+67SYx5s8/F1yabP03cXvARuBwx8ABOjzzlaxNFPWB7bh3ApRPn02nIZlI/YTI4dt0h6y41cHOWlR7kFUjPCdEiUUQEg8PXXfNtQ6hnefc8huJ7xkFExXxiVgSnOwVmbOmklURcZv/rQJGegC3HOLENJJ+subU+6Zrs7l+N6BcIQWCBEN+X2S3/4fXOiC/qOhYm0UZmiYgJRlxzWB5B5pbsT+cjD8rmI2hI+y7anM5lm+3ahipnX+MHwZV6uOld347KVzisyotLumk4=